{% set name = "libvterm" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.leonerd.org.uk/code/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 25a8ad9c15485368dfd0a8a9dca1aec8fea5c27da3fa74ec518d5d3787f0c397

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
    - make

test:
  commands:
    - test -f $PREFIX/lib/libvterm${SHLIB_EXT}

about:
  home: http://www.leonerd.org.uk/code/libvterm/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: C99 library which implements VT220 or xterm terminal emulator
  dev_url: http://www.leonerd.org.uk/code/libvterm/

extra:
  recipe-maintainers:
    - danielnachun
